### ISSUE TITLE
nextcloud_apache_php: false breaks on upgrade on nginx/fpm setup due to handlers

### ISSUE THREAD

**Issue by benaryorg** [systemli/ansible-role-nextcloud#26]
The handlers for Apache are invoked regardless of the setting of `nextcloud_apache_php`, therefore the upgrade procedure errs out at the handler stage.
Technically it'd be useful to also have a custom restart command for those cases (since FPM should be restarted after upgrading), but primarily a `when: nextcloud_apache_php` should be enough I guess.

Unless the intention of `nextcloud_apache_php` is not to enable other webservers but to stop managing certain aspects of apache, that is.
In which case a separate setting for those instances would be nice.

**Comment by t2d** [comment]
Thank you for raising this issue. The variable `nextcloud_apache_php` is there to disable specifics, that are just necessary in a plain apache+php config. Setting this to `false` doesn't necessarily mean that you don't use apache2 or php. A combination of apache2+php-fpm would also require `false`.

Anyhow, you're welcome to provide a patch which supports using this role with nginx. I think this will probably require more changes than just  `nextcloud_apache_php: false` as this role was developed to be used with apache.
