### ISSUE TITLE
Enable pretty urls

### ISSUE THREAD

**Issue by t2d** [systemli/ansible-role-nextcloud#4]
https://docs.nextcloud.com/server/16/admin_manual/installation/source_installation.html#pretty-urls
Atm it's only possible to do this by hand.
```
vi config/config.php
sudo chown user .htaccess
sudo -u user php ./occ maintenance:update:htaccess
sudo chown root .htaccess
```

**Comment by doobry-systemli** [comment]
We decided to not do this. You now can do the following:

```
nextcloud_config:
  system:
    htaccess.RewriteBase: '/'
```
