### ISSUE TITLE
config option to deactivated skelekton

### ISSUE THREAD

**Issue by unclesam87** [systemli/ansible-role-nextcloud#82]
hey, 
i am not quite sure how to achieve that:
i want to add the config option to deactivated the skeleton - but when i add the line like that 
    skeletondirectory: ''"

i get that error:
TASK [systemli.nextcloud : Nextcloud configure: copy skeleton directory] ***********************************************
fatal: [nextcloud.blabla]: FAILED! => {"changed": false, "msg": "dest is required"}

thanks for ur help

**Comment by doobry-systemli** [comment]
Can you explain what you try to achieve @unclesam87? What do you mean with "deactivate the skeleton"? You don't want any skeleton files to get copied to the folder of new users? Even not the default ones provided by Nextcloud? Then I'd suggest you create an empty directory on the server (e.g. `/usr/local/share/nextcloud/skeleton`) and put its path into the `skeletondirectory` variable.

**Comment by unclesam87** [comment]
yes i try to get an total empty folder

**Comment by doobry-systemli** [comment]
Fixed in #87
